[package]
name = "supasim-hal"
version.workspace = true
authors.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true
keywords.workspace = true
license.workspace = true

[features]
default = ["vulkan", "wgpu"]
cuda = [
  # "cust"
] # Potential cuda libraries: cust, cudarc
wgpu = ["dep:wgpu", "pollster"]
vulkan = ["ash", "gpu-allocator"]

[dependencies]
thiserror.workspace = true

types.workspace = true
shaders.workspace = true
anyhow.workspace = true
bytemuck.workspace = true
log.workspace = true
env_logger.workspace = true
scopeguard.workspace = true

# Vulkan dependencies
ash = { version = "0.38", optional = true }
gpu-allocator = { version = "0.27", optional = true, features = ["vulkan"] }

# WGPU dependencies
wgpu = { version = "24.0", optional = true, features = ["spirv"] }
pollster = { version = "0.4", optional = true }

# Cuda dependencies
# cust = { version = "0.3", optional = true }

# Test command: RUST_BACKTRACE=1 cargo test -- --nocapture --test-threads=1
