[workspace]
resolver = "2"
members = [
    "crates/supasim",
    "crates/supasim-hal",
    "crates/supasim-abstract",
    "crates/supasim-macros",
    "crates/supasim-shaders",
    "crates/supasim-types",
]

[workspace.package]
version = "0.0.1"
authors = ["SupaMaggie70 <supamaggie70@gmail.com>"]
repository = "https://github.com/supasim/supasim"
edition = "2021"
rust-version = "1.84"
keywords = ["hpc", "simulation"]
license = "GPL-3.0"


[workspace.dependencies]
anyhow = "1.0"
bitflags = "2.8"
bytemuck = { version = "1.21", features = ["derive"] }
env_logger = "0.11"
getrandom = "0.3"
libloading = "0.8"
log = { version = "0.4" }
nalgebra = "0.33"
rand = "0.9"
rayon = "1.10"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "2.0"
tempfile = "3.17"
scopeguard = "1.2"
daggy = "0.8.1"

abs = { package = "supasim-abstract", path = "crates/supasim-abstract" }
hal = { package = "supasim-hal", path = "crates/supasim-hal" }
macros = { package = "supasim-macros", path = "crates/supasim-macros" }
shaders = { package = "supasim-shaders", path = "crates/supasim-shaders" }
types = { package = "supasim-types", path = "crates/supasim-types" }
