[workspace]
resolver = "2"
members = ["supasim", "tests"]

[workspace.package]
version = "0.0.1"
authors = ["SupaMaggie70 <supamaggie70@gmail.com>"]
repository = "https://github.com/supamaggie70incorporated/supasim"
edition = "2021"
rust-version = "1.84"
keywords = ["hpc", "simulation"]


[workspace.dependencies]
anyhow = "1.0"
thiserror = "2.0"
bitflags = "2.8"
bytemuck = { version = "1.21", features = ["derive"] }
log = { version = "0.4" }
