[package]
name = "supasim"
version.workspace = true
authors.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true
keywords.workspace = true
license.workspace = true
readme = "../readme.md"

[dependencies]
paste = "1.0"

anyhow.workspace = true
thiserror.workspace = true

macros.workspace = true
shaders.workspace = true
types.workspace = true
hal.workspace = true
