name: SupaSim Main

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Download Vulkan SDK
      run: |
        export VULKAN_VERSION=1.4.304.0  # Change this to the desired version
        export INSTALL_DIR=$GITHUB_WORKSPACE/vulkan-sdk
        mkdir -p $INSTALL_DIR
        curl -L -o vulkan-sdk.tar.xz "https://sdk.lunarg.com/sdk/download/$VULKAN_VERSION/linux/vulkan-sdk.tar.xz"
        tar -xf vulkan-sdk.tar.xz --strip-components=1 -C $INSTALL_DIR
        export VULKAN_SDK="$INSTALL_DIR/1.4.304.0/x86_64"
        echo "VULKAN_SDK=$VULKAN_SDK" >> $GITHUB_ENV
        echo "SLANG_DIR=$VULKAN_SDK" >> $GITHUB_ENV # Slang is included in the sdk
        echo "SPIRV_TOOLS_DIR=$VULKAN_SDK" >> $GITHUB_ENV # Spirv tools is also included
        mv "$INSTALL_DIR/include/slang/*" "$INSTALL_DIR/include"

    - name: Build
      run: cargo build --verbose --all-targets --all-features
    - name: Clippy
      run: cargo clippy --verbose --all-targets --all-features
    - name: Run tests
      run: cargo test --verbose --all-targets --all-features
