name: SupaSim Main

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Download Slang
      run: |
        curl -L -o slang.tar.gz "https://github.com/shader-slang/slang/releases/download/v2025.5.1/slang-2025.5.1-linux-x86_64.tar.gz"
        mkdir slang-extracted
        tar -xzf slang.tar.gz -C slang-extracted
        echo "SLANG_DIR=$GITHUB_WORKSPACE/slang-extracted" >> $GITHUB_ENV
    - name: Download Vulkan SDK
      run: |
        export VULKAN_VERSION=1.4.304.0  # Change this to the desired version
        export INSTALL_DIR=$GITHUB_WORKSPACE/vulkan-sdk
        mkdir -p $INSTALL_DIR
        curl -L -o vulkan-sdk.tar.gz "https://sdk.lunarg.com/sdk/download/$VULKAN_VERSION/linux/vulkan-sdk.tar.gz"
        tar -xzf vulkan-sdk.tar.gz --strip-components=1 -C $INSTALL_DIR
        echo "VULKAN_SDK=$INSTALL_DIR" >> $GITHUB_ENV
    - name: Setup spirv-tools
      run: echo "SLANG_DIR=$GITHUB_WORKSPACE/.github/spirv-tools" >> $GITHUB_ENV

    - name: Build
      run: cargo build --verbose --all-targets --all-features
    - name: Clippy
      run: cargo clippy --verbose --all-targets --all-features
    - name: Run tests
      run: cargo test --verbose --all-targets --all-features
