name: SupaSim Main

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: download-slang
      run: |
        curl -L -o slang.tar.gz "https://github.com/shader-slang/slang/releases/download/v2025.5.1/slang-2025.5.1-linux-x86_64.tar.gz"
        mkdir slang-extracted
        tar -xzf slang.tar.gz -C slang-extracted
        echo "SLANG_DIR=$GITHUB_WORKSPACE/slang-extracted" >> $GITHUB_ENV
    - name: Build
      run: cargo build --verbose --all-targets --all-features
    - name: Clippy format
      run: cargo clippy --verbose --all-targets --all-features
    - name: Run tests
      run: cargo test --verbose --all-targets --all-features
